### ISSUE TITLE
The Art of Multi-Agent Coordination

### ISSUE THREAD

**Issue by Gurleen-Makkar** [pydelhi/talks#308]
### Title

The Art of Multi-Agent Coordination

### Describe your Talk

As multi-agent systems emerge as foundational components in the evolution of AI applications, this session explores their transformative role. We will first uncover why multi-agent architectures are key to future AI advancements, demonstrating how they surpass traditional approaches in adaptability, efficiency, and problem-solving. Then, we’ll examine diverse real-world applications, highlighting multi-agent implementations across industries such as finance and healthcare, where they are driving innovation. Through hands-on exercises, participants will engage with multi-agent coordination techniques, gaining practical insights into their orchestration and learning how to leverage them for robust, collaborative AI solutions.

### Pre-requisites & reading material

Acquaintance with coding

### Time required for the talk

1-2 hours

### About you

Gurleen and Keerthivasan ,we are Senior Consultants specializing in Generative AI at ThoughtWorks, where we lead AI-driven projects for one of India’s largest NBFCs. We focus on building scalable AI solutions that drive operational efficiency and create tangible impact. Together, we co-founded a Generative AI community , an initiative that promotes AI adoption and strengthens client engagement within ThoughtWorks.

### Availability

16/11/2024

**Comment by Gurleen-Makkar** [comment]
@kd100100 added

**Comment by Gurleen-Makkar** [comment]
Hi @Animesh-Ghosh...Slides are not there yet but i can put some talks we did in the same domain
https://youtu.be/AY3HoALxkf8?si=dKQQfNKfdgPbQNDn
https://youtu.be/9pjpau36bWI?si=AGLluv1IZd30qDyK

You can refer these

**Comment by Daksh777** [comment]
Hey @Gurleen-Makkar 
The talks from YouTube look good!

Though I wanted to mention one thing that in the meetup there would be people (mostly students) who don't know much about GenAI, and talking about multi agents could potentially be confusing for them. Do you think it would be possible for you to go over more of the basics/overview of the concept so that that audience is comfortable as well?

Also, is it possible for you to reduce the time required to around 40-45m? Since most of our talks would be around 20-ish minutes per speaker

**Comment by Daksh777** [comment]
Also, if you're okay with posting about your talk on our socials, could you share yours and @kd100100's picture?
