### ISSUE TITLE
Proposal: Start Mocking, Start Testing

### ISSUE THREAD

**Issue by dusual** [pydelhi/talks#5]
A talk on mock. And how you can use it to improve your test coverage. And create a nice framework for creating tests around your app.

Here's a preview
https://www.overleaf.com/read/kwxjyyvywgfz

---

- [x] slides
- [x] date finalization

**Comment by theskumar** [comment]
@dusual we have moved this talk to sept 5, please confirm if you'll be available on that day. 

Also, I checked https://www.overleaf.com/read/kwxjyyvywgfz the right pane says the presentation has not compiled yet. Since the rendered presentation is not visible it's little hard to see/read the content for everyone. possible to fix it? Thanks.

**Comment by theskumar** [comment]
@dusual moving this talk to 17th Oct. for voting. Confirm if you'll be available.

**Comment by dusual** [comment]
@theskumar  Yeah I can do this on 17th

**Comment by akshayaurora** [comment]
:+1:

**Comment by theskumar** [comment]
@dusual We are confirming you talk for 17th Oct. Wish you best of luck! :blush:

**Comment by aktech** [comment]
Talk status: Delivered
